[package]
name = "world_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".",
    "world_sys",
]
default-members = [
    ".",
    "world_sys",
]

[dependencies]
world_sys = { path = "./world_sys" }
