[package]
name = "world_sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.64.0"
cc = "1.0.78"
once_cell = "1.17.0"
regex = "1.7.0"
